// HERMES model of Firma Muster AG: phases, gates, deliverables and skills.
//
// Ported from prototype v22 and neutralized. Texts are placeholders until the
// PM-Handbuch and the "Szenarien-Ergebnis-Mapping" are available (todo-later P01).
// This file is configuration: the PMO maintains it, the engine interprets it.

import type { PhaseDef } from "./types";

export const PHASES: readonly PhaseDef[] = [
  {
    id: "init",
    label: "Initialisierung",
    description:
      "Definierte Ausgangslage schaffen und Projektziele mit den Zielen der Firma Muster AG abstimmen.",
    extension: false,
    gate: {
      name: "Projektfreigabe",
      deciderLabel: "Projektportfolio-Gremium und Auftraggeber",
      note: "Planungsgenauigkeit Aufwand und Kosten: +50 / −20 %.",
      deciders: ["PA"],
      globalDeciders: ["HH.Portfolio"],
      requiresKonsent: false,
    },
    deliverables: [
      {
        id: "pia",
        phase: "init",
        name: "Projektinitialisierungsauftrag",
        requirement: "pflicht",
        kind: "Dokument",
        skills: [],
        origin: "hermes",
        restricted: false,
        preExisting: {
          by: "Auftraggeber",
        },
      },
      {
        id: "kickoff",
        phase: "init",
        name: "Kick-off-Roundtable mit allen Beteiligten",
        requirement: "pflicht",
        kind: "Termin",
        skills: ["init.kick-off"],
        origin: "interviews",
        restricted: false,
      },
      {
        id: "studie",
        phase: "init",
        name: "Studie mit Lösungsvarianten",
        requirement: "pflicht",
        kind: "Dokument",
        skills: ["init.discovery", "init.anforderungen", "init.technische-koordination"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "vereinfachung",
        phase: "init",
        name: "Prozessvereinfachung geprüft (Standard vor Sonderlösung)",
        requirement: "pflicht",
        kind: "Prüfung",
        skills: ["init.anforderungen"],
        origin: "interviews",
        restricted: false,
      },
      {
        id: "recht",
        phase: "init",
        name: "Rechtsgrundlagenanalyse",
        requirement: "pflicht",
        kind: "Dokument",
        skills: ["init.legal"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "klass",
        phase: "init",
        name: "Datenklassifizierung und Cloud-Entscheid",
        requirement: "pflicht",
        kind: "Entscheid ISM",
        skills: ["init.datenklassifizierung"],
        origin: "interviews",
        restricted: true,
      },
      {
        id: "schuban",
        phase: "init",
        name: "Schutzbedarfsanalyse (SchuBAn), ausgefüllt im Fachbereich",
        requirement: "pflicht",
        kind: "Entscheid ISM",
        skills: ["init.schutzbedarf"],
        origin: "hermes",
        restricted: true,
      },
      {
        id: "dsvor",
        phase: "init",
        name: "Datenschutz-Vorabklärung",
        requirement: "pflicht",
        kind: "Abstimmung FDS",
        skills: ["init.datenschutz"],
        origin: "interviews",
        restricted: true,
      },
      {
        id: "forum",
        phase: "init",
        name: "Architekturforum (Ideation) zu den Varianten",
        requirement: "pflicht",
        kind: "Feedback",
        skills: ["init.architekturforum"],
        origin: "interviews",
        restricted: false,
      },
      {
        id: "variante",
        phase: "init",
        name: "Entscheid Variantenwahl",
        requirement: "pflicht",
        kind: "Entscheid PA",
        skills: ["init.bewerter"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "frueh",
        phase: "init",
        name: "Betriebs-Frühcheck",
        requirement: "pflicht",
        kind: "Dokument",
        skills: ["init.betrieb-light"],
        origin: "interviews",
        restricted: false,
      },
      {
        id: "pmp",
        phase: "init",
        name: "Projektmanagementplan",
        requirement: "pflicht",
        kind: "Dokument",
        skills: ["init.projektgrundlagen"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "auftrag",
        phase: "init",
        name: "Projektauftrag",
        requirement: "pflicht",
        kind: "Dokument",
        skills: ["init.projektgrundlagen"],
        origin: "hermes",
        restricted: false,
      },
    ],
    skills: [
      {
        id: "init.kick-off",
        phase: "init",
        name: "Kick-off",
        agent: "A2",
        mode: "ai-draft",
        mayStart: [],
        approvers: [],
        veto: false,
        description:
          "Holt alle Beteiligten der Phase an einen Tisch, verteilt Aufträge und hält Zuständigkeiten fest.",
        outputDoc: "Kick-off-Protokoll",
        sections: ["Teilnehmende", "Ziele und Rahmen", "Aufträge mit Verantwortlichen", "Offene Fragen"],
        isNew: true,
        origin: "hermes",
      },
      {
        id: "init.datenklassifizierung",
        phase: "init",
        name: "Datenklassifizierung",
        agent: "A5",
        mode: "ai-draft",
        mayStart: ["FACH", "ARCH"],
        approvers: [
          {
            role: "ISM",
            label: "ISM",
            konsent: false,
          },
        ],
        veto: false,
        description:
          "Klärt ganz am Anfang die Datenklassen und ob die Lösung in die Cloud darf; beides bestimmt die Varianten.",
        outputDoc: "Datenklassifizierung",
        sections: ["Datenarten", "Datenklasse", "Cloud-Entscheid mit Bedingungen", "Begründung"],
        isNew: true,
        origin: "hermes",
      },
      {
        id: "init.datenschutz",
        phase: "init",
        name: "Datenschutz",
        agent: "A5",
        mode: "ai-draft",
        mayStart: ["DS"],
        approvers: [
          {
            role: "DS",
            label: "Datenschutz",
            konsent: false,
          },
        ],
        veto: false,
        description:
          "Stimmt früh mit der Fachstelle Datenschutz ab, ob die Daten so erhoben und verwendet werden dürfen. Die DSFA wird erst vor dem Go-live abgeschlossen.",
        outputDoc: "Datenschutz-Vorabklärung",
        sections: [
          "Bearbeitete Personendaten",
          "Zweck und Rechtsgrundlage",
          "Löschfristen",
          "Weiteres Vorgehen (DSFA)",
        ],
        isNew: true,
        origin: "hermes",
      },
      {
        id: "init.architekturforum",
        phase: "init",
        name: "Architekturforum",
        agent: "A4",
        mode: "ai-draft",
        mayStart: ["ARCH"],
        approvers: [],
        veto: false,
        description:
          "Stellt die Varianten früh im Architekturforum vor und holt Feedback, bevor entschieden wird.",
        outputDoc: "Forums-Feedback",
        sections: ["Vorgestellte Varianten", "Hinweise des Forums", "Konsequenzen für die Varianten"],
        isNew: true,
        origin: "hermes",
      },
      {
        id: "init.discovery",
        phase: "init",
        name: "Discovery",
        agent: "A3",
        mode: "ai-draft",
        mayStart: ["BC"],
        approvers: [],
        veto: false,
        description: "Sammelt Ist-Stand, Kontext und ähnliche Vorhaben als Basis für die Studie.",
        outputDoc: "Studie, Kontext und Varianten",
        sections: ["Ausgangslage", "Kontext und Ist-Zustand", "Vergleichbare Vorhaben", "Lösungsvarianten"],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "init.anforderungen",
        phase: "init",
        name: "Anforderungen",
        agent: "A3",
        mode: "ai-draft",
        mayStart: ["BC", "FACH"],
        approvers: [],
        veto: false,
        description: "Erhebt und strukturiert die Grobanforderungen, inkl. Betriebs- und Skalierungsbedarf.",
        outputDoc: "Anforderungskatalog",
        sections: [
          "Grobanforderungen",
          "Priorisierung",
          "Betriebs- und Skalierungsbedarf",
          "Vereinfachungspotenzial (Standard vor Sonderlösung)",
        ],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "init.legal",
        phase: "init",
        name: "Legal",
        agent: "A6",
        mode: "ai-draft",
        mayStart: ["BC"],
        approvers: [],
        veto: false,
        description: "Prüft die Rechtsgrundlage des Vorhabens.",
        outputDoc: "Rechtsgrundlagenanalyse",
        sections: ["Sachverhalt", "Einschlägige Rechtsgrundlagen", "Beurteilung", "Offene Rechtsfragen"],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "init.schutzbedarf",
        phase: "init",
        name: "Schutzbedarf",
        agent: "A5",
        mode: "ai-draft",
        mayStart: ["FACH", "PA"],
        approvers: [
          {
            role: "ISM",
            label: "ISM",
            konsent: false,
          },
        ],
        veto: false,
        description:
          "Wird im Fachbereich ausgefüllt, weil dort das Wissen über die Daten liegt; das ISM prüft und berät. Bei relevanten Änderungen wird sie neu geprüft.",
        outputDoc: "SchuBAn",
        sections: [
          "Schutzobjekte",
          "Vertraulichkeit",
          "Integrität",
          "Verfügbarkeit",
          "Anforderungen an die Notfallplanung",
        ],
        isNew: true,
        origin: "hermes",
      },
      {
        id: "init.bewerter",
        phase: "init",
        name: "Bewerter",
        agent: "A3",
        mode: "ai-draft",
        mayStart: [],
        approvers: [
          {
            role: "PA",
            label: "Projektausschuss",
            konsent: true,
          },
        ],
        veto: false,
        description: "Bewertet die Lösungsvarianten und schätzt den Aufwand grob.",
        outputDoc: "Variantenbewertung",
        sections: [
          "Varianten im Vergleich",
          "Aufwandschätzung mit Quellen",
          "Risiken",
          "Antrag an den Projektausschuss",
        ],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "init.projektgrundlagen",
        phase: "init",
        name: "Projektgrundlagen",
        agent: "A2",
        mode: "ai-draft",
        mayStart: [],
        approvers: [],
        veto: false,
        description:
          "Entwirft Projektmanagementplan und Projektauftrag aus Studie und Variantenentscheid, inkl. Ressourcenbedarf für die Ressourcenplanung.",
        outputDoc: "Projektmanagementplan und Projektauftrag (Entwurf)",
        sections: [
          "Ausgangslage und Ziele",
          "Lieferobjekte und Abgrenzung",
          "Projektorganisation",
          "Vorgehen und Meilensteine",
          "Kosten und Ressourcen",
          "Qualitätssicherung",
          "Risiken",
        ],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "init.technische-koordination",
        phase: "init",
        name: "Technische Koordination",
        agent: "A4",
        mode: "ai-draft",
        mayStart: ["INFRA"],
        approvers: [],
        veto: false,
        description:
          "Wirkt als Solution Architecture schon vor der Ausschreibung: skizziert Liefermodelle, Integrationsmodell und Cloud- oder On-Premises-Einordnung und bereitet technische Mindestkriterien vor.",
        outputDoc: "Technisches Liefermodell (Entwurf)",
        sections: [
          "Liefermodelle",
          "Integrationsmodell",
          "Cloud- oder On-Premises-Einordnung",
          "Technische Mindestkriterien",
        ],
        isNew: true,
        origin: "interviews",
      },
      {
        id: "init.betrieb-light",
        phase: "init",
        name: "Betrieb (Light)",
        agent: "A8",
        mode: "ai-draft",
        mayStart: ["APM"],
        approvers: [],
        veto: false,
        description: "Bringt die Betriebssicht früh ein statt erst in der Einführung.",
        outputDoc: "Betriebs-Frühcheck",
        sections: ["Betriebsanforderungen", "Schnittstellen", "Offene Fragen an den Betrieb"],
        isNew: true,
        origin: "hermes",
      },
    ],
  },
  {
    id: "konzept",
    label: "Konzept",
    description:
      "Die gewählte Variante so konkretisieren, dass das IT-System verlässlich geplant, offeriert und realisiert werden kann.",
    extension: false,
    gate: {
      name: "Phasenfreigabe Realisierung",
      deciderLabel: "Projektausschuss",
      note: "Planungsgenauigkeit: ±15 %. Das PPM-Gremium kann situativ mitentscheiden.",
      deciders: ["PA"],
      globalDeciders: [],
      requiresKonsent: true,
    },
    deliverables: [
      {
        id: "sysanf",
        phase: "konzept",
        name: "Systemanforderungen",
        requirement: "pflicht",
        kind: "Dokument",
        skills: ["konzept.business-analyse"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "sysarch",
        phase: "konzept",
        name: "Systemarchitektur mit Freigabe Architektur-Board",
        requirement: "pflicht",
        kind: "Entscheid Architektur-Board",
        skills: ["konzept.pattern-pilot", "konzept.technische-koordination", "konzept.architekt"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "isds",
        phase: "konzept",
        name: "ISDS-Konzept",
        requirement: "pflicht",
        kind: "Entscheid ISM",
        skills: ["konzept.security-engineering", "konzept.isds"],
        origin: "hermes",
        restricted: true,
      },
      {
        id: "testk",
        phase: "konzept",
        name: "Testkonzept",
        requirement: "pflicht",
        kind: "Dokument",
        skills: ["konzept.test-engineer"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "einfk",
        phase: "konzept",
        name: "Einführungskonzept",
        requirement: "pflicht",
        kind: "Dokument",
        skills: ["konzept.einfuehrungsplanung"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "pbk",
        phase: "konzept",
        name: "Phasenbericht und nachgeführter PMP",
        requirement: "pflicht",
        kind: "Dokument",
        skills: ["konzept.phasenbericht"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "poc",
        phase: "konzept",
        name: "Prototyp / Proof of Concept",
        requirement: "situativ",
        kind: "Ergebnis",
        skills: ["konzept.engineer"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "submission",
        phase: "konzept",
        name: "Submission und Vergabeentscheid",
        requirement: "situativ",
        kind: "Entscheid PA",
        skills: ["konzept.pattern-pilot", "konzept.beschaffung"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "scrum",
        phase: "konzept",
        name: "Entscheid agile Entwicklung, Roadmap, DoR/DoD",
        requirement: "situativ",
        kind: "Entscheid PA",
        skills: ["konzept.scrum-setup"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "ux",
        phase: "konzept",
        name: "Wireframes",
        requirement: "situativ",
        kind: "Dokument",
        skills: ["konzept.designer"],
        origin: "erweiterung",
        restricted: false,
      },
    ],
    skills: [
      {
        id: "konzept.pattern-pilot",
        phase: "konzept",
        name: "Pattern-Pilot",
        agent: "A4",
        mode: "ai-draft",
        mayStart: ["BC"],
        approvers: [
          {
            role: "ARCH",
            label: "IT-Architektur",
            konsent: false,
          },
        ],
        veto: false,
        description:
          "Gleicht Ausschreibungsunterlagen und Lieferantenkonzept mit den Vorgaben der Firma Muster AG ab (Architektur-Patterns, Referenzarchitektur, Security- und Betriebskriterien), leitet die Muss-Kriterien fürs Pflichtenheft ab und zeichnet die Systemskizze im Firmenstandard nach. Die Architektur prüft nur die markierten Abweichungen.",
        outputDoc: "Prüfbericht Architektur-Vorabcheck",
        sections: [
          "Geprüfte Patterns",
          "Abweichungen",
          "Muss-Kriterien für das Pflichtenheft",
          "Systemskizze",
        ],
        isNew: true,
        origin: "interviews",
      },
      {
        id: "konzept.technische-koordination",
        phase: "konzept",
        name: "Technische Koordination",
        agent: "A4",
        mode: "ai-draft",
        mayStart: ["INFRA"],
        approvers: [],
        veto: false,
        description:
          "Stimmt Umgebungsdesign und Aufwand mit der Infrastruktur ab und holt eine verbindliche Kapazitätszusage. Tickets entstehen erst danach, als Ergebnis der gemeinsamen Klärung.",
        outputDoc: "Umgebungsdesign und Kapazitätszusage",
        sections: [
          "Umgebungsdesign (Test, Abnahme, Produktion)",
          "Aufwand der Infrastruktur",
          "Kapazitätszusage",
        ],
        isNew: true,
        origin: "interviews",
      },
      {
        id: "konzept.security-engineering",
        phase: "konzept",
        name: "Security Engineering",
        agent: "A5",
        mode: "ai-draft",
        mayStart: ["ISM", "INFRA"],
        approvers: [],
        veto: false,
        description:
          "Übersetzt den Schutzbedarf zusammen mit der Infrastruktur in umsetzbare technische Massnahmen, bevor das ISDS-Konzept geschrieben wird.",
        outputDoc: "Technische Sicherheitsmassnahmen",
        sections: [
          "Schutzbedarf (Bezug SchuBAn)",
          "Technische Massnahmen",
          "Umsetzbarkeit mit der Infrastruktur",
        ],
        isNew: true,
        origin: "interviews",
      },
      {
        id: "konzept.business-analyse",
        phase: "konzept",
        name: "Business-Analyse",
        agent: "A3",
        mode: "ai-draft",
        mayStart: ["BC"],
        approvers: [],
        veto: false,
        description:
          "Überführt die Anforderungen zusammen mit Sachbearbeitenden in Systemanforderungen, Epics und User Stories, inklusive Alternativpfaden.",
        outputDoc: "Systemanforderungen",
        sections: [
          "Systemkontext",
          "Epics und User Stories",
          "Alternativpfade (Rückweisung, Nachforderung)",
          "Akzeptanzkriterien",
          "Nicht-funktionale Anforderungen",
        ],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "konzept.architekt",
        phase: "konzept",
        name: "Architekt",
        agent: "A4",
        mode: "ai-draft",
        mayStart: ["ARCH"],
        approvers: [
          {
            role: "ARCH",
            label: "Architektur-Board",
            konsent: false,
          },
        ],
        veto: false,
        description:
          "Erarbeitet die Systemarchitektur, stellt sie im Forum vor und holt die Freigabe des Architektur-Boards, bevor gebaut wird.",
        outputDoc: "Systemarchitektur",
        sections: [
          "Architekturübersicht",
          "Komponenten und Schnittstellen",
          "Betrieb und Sicherheit",
          "Architekturentscheide",
        ],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "konzept.isds",
        phase: "konzept",
        name: "ISDS",
        agent: "A5",
        mode: "ai-draft",
        mayStart: ["ISM", "DS"],
        approvers: [
          {
            role: "ISM",
            label: "ISM",
            konsent: false,
          },
        ],
        veto: true,
        description:
          "Erstellt das ISDS-Konzept mit Massnahmen und Praxisbezug zur Infrastruktur; wird bei relevanten Änderungen neu geprüft.",
        outputDoc: "ISDS-Konzept",
        sections: [
          "Schutzbedarf",
          "Technische und organisatorische Massnahmen",
          "Restrisiken mit Verantwortlichen",
        ],
        isNew: true,
        origin: "hermes",
      },
      {
        id: "konzept.test-engineer",
        phase: "konzept",
        name: "Test-Engineer",
        agent: "A7",
        mode: "ai-draft",
        mayStart: ["TEST"],
        approvers: [],
        veto: false,
        description: "Definiert Testkonzept, Teststufen und Mängelklassen.",
        outputDoc: "Testkonzept",
        sections: [
          "Teststufen",
          "Mängelklassen",
          "Abnahmekriterien je Klasse",
          "Testumgebungen",
          "Testdaten",
        ],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "konzept.einfuehrungsplanung",
        phase: "konzept",
        name: "Einführungsplanung",
        agent: "A8",
        mode: "ai-draft",
        mayStart: ["FACH"],
        approvers: [],
        veto: false,
        description: "Plant Einführung, Schulung und Kommunikation bis zur Betriebsaufnahme.",
        outputDoc: "Einführungskonzept",
        sections: ["Einführungsstrategie", "Schulung", "Kommunikation", "Umstellung und Rückfallebene"],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "konzept.phasenbericht",
        phase: "konzept",
        name: "Phasenbericht",
        agent: "A2",
        mode: "ai-draft",
        mayStart: [],
        approvers: [],
        veto: false,
        description:
          "Führt den Projektmanagementplan nach und erstellt den Phasenbericht für den Projektausschuss.",
        outputDoc: "Phasenbericht Konzept",
        sections: [
          "Stand der Ergebnisse",
          "Kosten und Termine (±15 %)",
          "Risiken",
          "Antrag an den Projektausschuss",
        ],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "konzept.engineer",
        phase: "konzept",
        name: "Engineer",
        agent: "A4",
        mode: "ai-draft",
        mayStart: ["ARCH"],
        approvers: [],
        veto: false,
        description: "Prüft die technische Machbarkeit, bei Bedarf mit Prototyp.",
        outputDoc: "Machbarkeitsbericht",
        sections: ["Fragestellung", "Vorgehen", "Ergebnis", "Risiken"],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "konzept.beschaffung",
        phase: "konzept",
        name: "Beschaffung",
        agent: "A6",
        mode: "ai-draft",
        mayStart: [],
        approvers: [
          {
            role: "PA",
            label: "Projektausschuss",
            konsent: true,
          },
        ],
        veto: false,
        description:
          "Bereitet Pflichtenheft und Submission vor und unterstützt den Vergabeentscheid. Übernimmt die Muss-Kriterien des Pattern-Pilot; ein Kriterium aufzuweichen braucht eine Begründung und die Risikoübernahme durch den Projektausschuss.",
        outputDoc: "Pflichtenheft",
        sections: ["Muss-Kriterien", "Bewertungskriterien", "Verfahren", "Vergabeantrag"],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "konzept.scrum-setup",
        phase: "konzept",
        name: "Scrum-Setup",
        agent: "A3",
        mode: "ai-draft",
        mayStart: [],
        approvers: [
          {
            role: "PA",
            label: "Projektausschuss",
            konsent: true,
          },
        ],
        veto: false,
        description:
          "Bereitet den Entscheid zur agilen Entwicklung vor: Rollenbesetzung, Roadmap, DoR und DoD gemäss Guideline.",
        outputDoc: "Roadmap agile Entwicklung",
        sections: ["Rollenbesetzung", "Roadmap", "Definition of Ready", "Definition of Done"],
        isNew: true,
        origin: "hermes",
      },
      {
        id: "konzept.designer",
        phase: "konzept",
        name: "Designer",
        agent: "A3",
        mode: "ai-draft",
        mayStart: ["BC", "ARCH"],
        approvers: [],
        veto: false,
        description:
          "Erstellt Mockups, damit Fach und Entwicklung dasselbe verstehen. Ein Mockup ist kein Produkt: umgesetzt wird mit dem Designsystem, Wartung und Security im Blick.",
        outputDoc: "Wireframes",
        sections: ["Zielgruppen", "Screens", "Offene Fragen an das Fach"],
        isNew: false,
        origin: "hermes",
      },
    ],
  },
  {
    id: "real",
    label: "Realisierung",
    description:
      "Das IT-System realisieren und testen, Einführungsrisiken minimieren und die ISDS-Massnahmen umsetzen.",
    extension: false,
    gate: {
      name: "Phasenfreigabe Einführung",
      deciderLabel: "Projektausschuss",
      note: "Basiert auf dem Entscheid Vorabnahme; die Einführungsrisiken müssen vertretbar sein.",
      deciders: ["PA"],
      globalDeciders: [],
      requiresKonsent: true,
    },
    deliverables: [
      {
        id: "infra",
        phase: "real",
        name: "Infrastruktur bereitgestellt (Umgebungen, Firewall, AD-Gruppen)",
        requirement: "pflicht",
        kind: "Ergebnis",
        skills: ["real.technische-koordination"],
        origin: "interviews",
        restricted: false,
      },
      {
        id: "readiness",
        phase: "real",
        name: "Readiness-Check: Zugänge von allen getestet",
        requirement: "pflicht",
        kind: "Nachweis",
        skills: ["real.technische-koordination"],
        origin: "interviews",
        restricted: false,
        checklist: {
          title: "Readiness-Check: Zugänge getestet",
          availableAfterSkill: "real.technische-koordination",
          requiredFor: "release",
          items: [
            {
              id: "lieferant",
              label: "Lieferant (Entwicklung)",
              ownerRole: "INFRA",
            },
            {
              id: "apm",
              label: "APM",
              ownerRole: "APM",
            },
            {
              id: "fachtest",
              label: "Fachtester (Fachstelle)",
              ownerRole: "FACH",
            },
            {
              id: "entwicklung",
              label: "Interne Entwicklung",
              ownerRole: "ARCH",
            },
          ],
        },
      },
      {
        id: "system",
        phase: "real",
        name: "IT-System realisiert (Release-Kandidat)",
        requirement: "pflicht",
        kind: "Ergebnis",
        skills: ["real.executer"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "dsfa",
        phase: "real",
        name: "DSFA abgeschlossen (vor Go-live)",
        requirement: "pflicht",
        kind: "Entscheid FDS",
        skills: ["real.datenschutz"],
        origin: "hermes",
        restricted: true,
      },
      {
        id: "testprot",
        phase: "real",
        name: "Testprotokoll",
        requirement: "pflicht",
        kind: "Dokument",
        skills: ["real.integrationstest"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "isdsum",
        phase: "real",
        name: "Umsetzung ISDS-Massnahmen",
        requirement: "pflicht",
        kind: "Nachweis ISM",
        skills: ["real.security-pruefer"],
        origin: "hermes",
        restricted: true,
      },
      {
        id: "vorab",
        phase: "real",
        name: "Entscheid Vorabnahme",
        requirement: "pflicht",
        kind: "Entscheid PL",
        skills: ["real.user-acceptance"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "einfrisk",
        phase: "real",
        name: "Beurteilung Einführungsrisiken",
        requirement: "pflicht",
        kind: "Dokument",
        skills: ["real.phasenbericht"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "backlog",
        phase: "real",
        name: "Product Backlog und Sprintplanung",
        requirement: "situativ",
        kind: "Dokument",
        skills: ["real.sprint-planer"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "extsec",
        phase: "real",
        name: "Externe Sicherheitsüberprüfung",
        requirement: "situativ",
        kind: "Nachweis",
        skills: ["real.security-pruefer"],
        origin: "hermes",
        restricted: true,
      },
      {
        id: "handb",
        phase: "real",
        name: "Betriebs- und Anwendungshandbuch",
        requirement: "situativ",
        kind: "Dokument",
        skills: ["real.handbuecher"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "migr",
        phase: "real",
        name: "Probemigration",
        requirement: "situativ",
        kind: "Ergebnis",
        skills: ["real.datenmigration"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "a11y",
        phase: "real",
        name: "Prüfbericht Barrierefreiheit",
        requirement: "situativ",
        kind: "Dokument",
        skills: ["real.barrierefreiheit"],
        origin: "erweiterung",
        restricted: false,
      },
    ],
    skills: [
      {
        id: "real.technische-koordination",
        phase: "real",
        name: "Technische Koordination",
        agent: "A4",
        mode: "ai-draft",
        mayStart: ["INFRA"],
        approvers: [],
        veto: false,
        description:
          "Bündelt Server-, Firewall- und AD-Bestellungen in der richtigen Reihenfolge und ist Ansprechperson für Lieferant und Entwicklung.",
        outputDoc: "Infrastruktur-Bestellplan",
        sections: [
          "Umgebungen (Test, Abnahme, Produktion)",
          "Firewall-Regeln mit Quelle und Ziel",
          "Berechtigungsgruppen je Instanz",
          "Readiness-Check der Zugänge",
        ],
        isNew: true,
        origin: "hermes",
      },
      {
        id: "real.datenschutz",
        phase: "real",
        name: "Datenschutz",
        agent: "A5",
        mode: "ai-draft",
        mayStart: ["DS"],
        approvers: [
          {
            role: "DS",
            label: "Datenschutz",
            konsent: false,
          },
        ],
        veto: false,
        description: "Schliesst die DSFA ab, sobald die Lösung feststeht, inklusive Löschfristen.",
        outputDoc: "DSFA",
        sections: [
          "Beschreibung der Bearbeitung",
          "Risiken für Betroffene",
          "Massnahmen",
          "Löschfristen",
          "Restrisiken mit Verantwortlichen",
        ],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "real.executer",
        phase: "real",
        name: "Executer",
        agent: null,
        mode: "manual",
        mayStart: ["ARCH"],
        approvers: [],
        veto: false,
        description: "Führt Tickets und Deployments auf die Testumgebung aus.",
        outputDoc: "Deployment-Log",
        sections: ["Release-Kandidat", "Umgesetzte Anforderungen", "Bekannte Einschränkungen"],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "real.integrationstest",
        phase: "real",
        name: "Integrationstest",
        agent: null,
        mode: "manual",
        mayStart: ["TEST", "ARCH"],
        approvers: [],
        veto: false,
        description: "Führt Schnittstellen- und Regressionstests bei jedem Build automatisiert aus.",
        outputDoc: "Testprotokoll",
        sections: ["Ausgeführte Tests", "Ergebnisse", "Fehler nach Mängelklasse"],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "real.security-pruefer",
        phase: "real",
        name: "Security-Prüfer",
        agent: "A5",
        mode: "ai-draft",
        mayStart: ["ARCH", "APM"],
        approvers: [
          {
            role: "ISM",
            label: "ISM",
            konsent: false,
          },
        ],
        veto: false,
        description:
          "Prüft die Umsetzung der ISDS-Massnahmen vor jedem Release, bei hoher ISDS-Relevanz mit externem Dienstleister.",
        outputDoc: "Sicherheitsbericht",
        sections: ["Prüfumfang", "Umgesetzte Massnahmen", "Findings", "Massnahmen bis zum nächsten Release"],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "real.user-acceptance",
        phase: "real",
        name: "User Acceptance",
        agent: "A7",
        mode: "ai-draft",
        mayStart: ["FACH", "TEST"],
        approvers: [
          {
            role: "PL",
            label: "Projektleitung",
            konsent: false,
          },
        ],
        veto: false,
        description: "Führt mit den Anwendervertretern die Vorabnahme durch und klassiert Fehler.",
        outputDoc: "Vorabnahmeprotokoll",
        sections: [
          "Testfälle und Ergebnisse",
          "Fehler nach Mängelklasse",
          "Fehlerbehebung mit Termin",
          "Entscheidvorschlag",
        ],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "real.phasenbericht",
        phase: "real",
        name: "Phasenbericht",
        agent: "A2",
        mode: "ai-draft",
        mayStart: [],
        approvers: [],
        veto: false,
        description: "Beurteilt die Einführungsrisiken und erstellt den Phasenbericht Realisierung.",
        outputDoc: "Phasenbericht Realisierung",
        sections: ["Einführungsrisiken", "Bewertung", "Massnahmen", "Antrag an den Projektausschuss"],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "real.sprint-planer",
        phase: "real",
        name: "Sprint-Planer",
        agent: "A3",
        mode: "ai-draft",
        mayStart: ["FACH", "ARCH"],
        approvers: [],
        veto: false,
        description: "Zerlegt die Systemanforderungen in Sprints und hält das Backlog priorisiert.",
        outputDoc: "Backlog",
        sections: ["Product Backlog", "Sprintplanung", "Abhängigkeiten"],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "real.handbuecher",
        phase: "real",
        name: "Handbücher",
        agent: "A8",
        mode: "ai-draft",
        mayStart: ["APM", "FACH"],
        approvers: [],
        veto: false,
        description: "Erstellt Betriebs- und Anwendungshandbuch, knapp und betriebstauglich.",
        outputDoc: "Betriebshandbuch",
        sections: ["Betriebshandbuch", "Anwendungshandbuch", "SLA und Eskalation"],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "real.datenmigration",
        phase: "real",
        name: "Datenmigration",
        agent: "A4",
        mode: "ai-draft",
        mayStart: ["ARCH", "APM"],
        approvers: [],
        veto: false,
        description: "Plant die Übernahme von Altdaten und prüft sie mit Probemigrationen.",
        outputDoc: "Migrationsprotokoll",
        sections: ["Datenumfang", "Ergebnis der Probemigration", "Bereinigung"],
        isNew: true,
        origin: "hermes",
      },
      {
        id: "real.barrierefreiheit",
        phase: "real",
        name: "Barrierefreiheit",
        agent: "A7",
        mode: "ai-draft",
        mayStart: ["TEST", "FACH"],
        approvers: [],
        veto: false,
        description: "Prüft die Oberflächen gegen WCAG 2.1 AA, bevor externe Nutzende sie verwenden.",
        outputDoc: "Prüfbericht Barrierefreiheit",
        sections: ["Prüfumfang", "Befunde", "Massnahmen"],
        isNew: true,
        origin: "hermes",
      },
    ],
  },
  {
    id: "einf",
    label: "Einführung",
    description:
      "Sicherer Übergang vom alten zum neuen Zustand, Betriebsaufnahme, Abnahme und Projektabschluss.",
    extension: false,
    gate: {
      name: "Projektabschluss",
      deciderLabel: "Projektausschuss",
      note: "Vor der Betriebsaufnahme steht das Go-live-Gate mit Veto von Fachstelle und APM. Das Projektportfolio-Gremium nimmt den Abschluss zur Kenntnis.",
      deciders: ["PA"],
      globalDeciders: [],
      requiresKonsent: true,
    },
    deliverables: [
      {
        id: "massn",
        phase: "einf",
        name: "Einführungsmassnahmen und Schulung",
        requirement: "pflicht",
        kind: "Ergebnis",
        skills: ["einf.einfuehrung"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "persona",
        phase: "einf",
        name: "End-to-End- und Non-Happy-Path-Tests aus Nutzersicht",
        requirement: "pflicht",
        kind: "Nachweis",
        skills: ["einf.testpersona"],
        origin: "interviews",
        restricted: false,
      },
      {
        id: "golive",
        phase: "einf",
        name: "Go-live-Gate: fachliche und betriebliche Bereitschaft",
        requirement: "pflicht",
        kind: "Entscheid Fachstelle und APM",
        skills: ["einf.go-live-check"],
        origin: "interviews",
        restricted: false,
      },
      {
        id: "restm",
        phase: "einf",
        name: "Restmängelliste mit Frist und Verantwortung",
        requirement: "pflicht",
        kind: "Dokument",
        skills: ["einf.go-live-check"],
        origin: "interviews",
        restricted: false,
      },
      {
        id: "betrieb",
        phase: "einf",
        name: "Entscheid Betriebsaufnahme",
        requirement: "pflicht",
        kind: "Entscheid PA",
        skills: ["einf.betrieb"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "abnahme",
        phase: "einf",
        name: "Entscheid Abnahme",
        requirement: "pflicht",
        kind: "Entscheid Auftraggeber",
        skills: ["einf.fachtester"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "schluss",
        phase: "einf",
        name: "Projektschlussbeurteilung inkl. offene Punkte",
        requirement: "pflicht",
        kind: "Dokument",
        skills: ["einf.projektabschluss"],
        origin: "hermes",
        restricted: false,
      },
      {
        id: "migrab",
        phase: "einf",
        name: "Abnahme Migration",
        requirement: "situativ",
        kind: "Entscheid",
        skills: ["einf.betrieb"],
        origin: "hermes",
        restricted: false,
      },
    ],
    skills: [
      {
        id: "einf.einfuehrung",
        phase: "einf",
        name: "Einführung",
        agent: "A8",
        mode: "ai-draft",
        mayStart: ["FACH"],
        approvers: [],
        veto: false,
        description: "Setzt Schulung, Kommunikation und Umstellung gemäss Einführungskonzept um.",
        outputDoc: "Einführungsprotokoll",
        sections: ["Durchgeführte Schulungen", "Kommunikation", "Umstellung"],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "einf.go-live-check",
        phase: "einf",
        name: "Go-live-Check",
        agent: "A7",
        mode: "ai-draft",
        mayStart: ["TEST"],
        approvers: [
          {
            role: "FACH",
            label: "Fachstelle",
            konsent: false,
          },
          {
            role: "APM",
            label: "APM",
            konsent: false,
          },
        ],
        veto: true,
        description:
          "Stellt fachliche und betriebliche Bereitschaft zusammen: End-to-End- und Non-Happy-Path-Tests, Schulungsstand, Kommunikation und Restmängel. Fachstelle und APM haben Vetorecht; technisch fertig heisst nicht bereit.",
        outputDoc: "Go-live-Readiness-Bericht",
        sections: [
          "Fachliche Bereitschaft",
          "Betriebliche Bereitschaft",
          "End-to-End- und Non-Happy-Path-Tests",
          "Restmängel mit Frist und Verantwortung",
          "Empfehlung",
        ],
        isNew: true,
        origin: "interviews",
        checklist: {
          title: "Go-live-Kriterien",
          availableAfterSkill: "einf.go-live-check",
          requiredFor: "approval",
          items: [
            {
              id: "fach",
              label: "Fachliche Abnahme durch Sachbearbeitende mit realen Fällen",
              ownerRole: "FACH",
            },
            {
              id: "betr",
              label: "Betriebliche Abnahme: Umgebungen, Zugänge, Supportwege, SLA, Störfallablauf",
              ownerRole: "APM",
            },
            {
              id: "e2e",
              label: "End-to-End-Tests von ausserhalb des Firmennetzes, inkl. Wartezeiten wie Berechtigungen",
              ownerRole: "FACH",
            },
            {
              id: "nhp",
              label: "Non-Happy-Path getestet: Rückweisung, Nachforderung, Fehlerfälle",
              ownerRole: "FACH",
            },
            {
              id: "schul",
              label: "Schulung abgeschlossen, die Nutzenden fühlen sich sicher",
              ownerRole: "FACH",
            },
            {
              id: "komm",
              label: "Externe Nutzende mit Handlungsbedarf informiert",
              ownerRole: "PL",
            },
            {
              id: "rest",
              label: "Restmängel mit Frist und Verantwortung dokumentiert, keine Klasse 1 offen",
              ownerRole: "PL",
            },
          ],
        },
      },
      {
        id: "einf.betrieb",
        phase: "einf",
        name: "Betrieb",
        agent: "A8",
        mode: "ai-draft",
        mayStart: ["APM"],
        approvers: [
          {
            role: "PA",
            label: "Projektausschuss",
            konsent: true,
          },
        ],
        veto: false,
        description:
          "Bereitet Betriebsübergabe und den Entscheid Betriebsaufnahme vor, inkl. SLA-Check. Setzt ein bestandenes Go-live-Gate voraus.",
        outputDoc: "Betriebsübergabe",
        sections: [
          "Betriebsübergabe",
          "SLA",
          "Eskalationskontakt",
          "Abnahme Migration",
          "Antrag Betriebsaufnahme",
        ],
        isNew: false,
        origin: "hermes",
        requiresApproved: ["einf.go-live-check"],
      },
      {
        id: "einf.fachtester",
        phase: "einf",
        name: "Fachtester",
        agent: "A7",
        mode: "ai-draft",
        mayStart: ["FACH"],
        approvers: [
          {
            role: "PA",
            label: "Auftraggeber",
            konsent: false,
          },
        ],
        veto: false,
        description: "Führt die fachliche Abnahme durch.",
        outputDoc: "Abnahmeprotokoll",
        sections: ["Testfälle", "Ergebnis", "Vorbehalte", "Antrag Abnahme"],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "einf.projektabschluss",
        phase: "einf",
        name: "Projektabschluss",
        agent: "A2",
        mode: "ai-draft",
        mayStart: [],
        approvers: [],
        veto: false,
        description:
          "Erstellt die Projektschlussbeurteilung mit Lessons Learned und übergibt offene Punkte an die Stammorganisation.",
        outputDoc: "Projektschlussbeurteilung",
        sections: ["Zielerreichung", "Kosten und Termine", "Lessons Learned", "Offene Punkte an die Linie"],
        isNew: false,
        origin: "hermes",
      },
      {
        id: "einf.testpersona",
        phase: "einf",
        name: "Testpersona",
        agent: "A7",
        mode: "ai-draft",
        mayStart: ["TEST", "BC"],
        approvers: [],
        veto: false,
        description:
          "Spielt reale Abläufe von ausserhalb des Firmennetzes durch, inklusive Rückweisungen, Nachforderungen und Wartezeiten.",
        outputDoc: "End-to-End-Testprotokoll",
        sections: ["Nutzerprofile", "Szenarien", "Non-Happy-Path", "Befunde"],
        isNew: false,
        origin: "hermes",
      },
    ],
  },
  {
    id: "skal",
    label: "Skalierung",
    description:
      "Nach dem Projektabschluss: Wirkung belegen und die Lösung für weitere Bereiche nutzbar machen.",
    extension: true,
    gate: {
      name: "Skalierungsentscheid",
      deciderLabel: "Leitung / Projektportfolio-Gremium",
      note: "Ergänzung, nicht Teil von HERMES 5.1 bzw. des PM-Handbuchs.",
      deciders: ["PA"],
      globalDeciders: ["HH.Portfolio"],
      requiresKonsent: false,
    },
    deliverables: [
      {
        id: "wert",
        phase: "skal",
        name: "Wertnachweis-Bericht",
        requirement: "pflicht",
        kind: "Dokument",
        skills: ["skal.wertnachweis"],
        origin: "erweiterung",
        restricted: false,
      },
      {
        id: "rollout",
        phase: "skal",
        name: "Rollout-Paket",
        requirement: "situativ",
        kind: "Ergebnis",
        skills: ["skal.rollout"],
        origin: "erweiterung",
        restricted: false,
      },
      {
        id: "referenz",
        phase: "skal",
        name: "Referenzfall",
        requirement: "situativ",
        kind: "Dokument",
        skills: ["skal.referenz"],
        origin: "erweiterung",
        restricted: false,
      },
      {
        id: "ausm",
        phase: "skal",
        name: "Ausmusterungsvorschlag",
        requirement: "situativ",
        kind: "Dokument",
        skills: ["skal.ausmusterung"],
        origin: "erweiterung",
        restricted: false,
      },
    ],
    skills: [
      {
        id: "skal.wertnachweis",
        phase: "skal",
        name: "Wertnachweis",
        agent: "A2",
        mode: "ai-draft",
        mayStart: ["PA"],
        approvers: [],
        veto: false,
        description: "Sammelt KPIs und belegt die tatsächliche Wertrealisierung.",
        outputDoc: "Wertnachweis-Bericht",
        sections: ["KPI-Basislinie", "Wirkung seit Einführung", "Folgerungen"],
        isNew: true,
        origin: "hermes",
      },
      {
        id: "skal.rollout",
        phase: "skal",
        name: "Rollout",
        agent: "A8",
        mode: "ai-draft",
        mayStart: ["APM"],
        approvers: [],
        veto: false,
        description: "Bereitet Schulung, Dokumentation und Konfiguration für weitere Bereiche vor.",
        outputDoc: "Rollout-Paket",
        sections: ["Zielbereiche", "Schulung und Dokumentation", "Konfiguration"],
        isNew: true,
        origin: "hermes",
      },
      {
        id: "skal.referenz",
        phase: "skal",
        name: "Referenz",
        agent: "A2",
        mode: "ai-draft",
        mayStart: ["PA"],
        approvers: [],
        veto: false,
        description: "Macht erfolgreiche Projekte als Referenz für andere Bereiche sichtbar.",
        outputDoc: "Referenzfall",
        sections: ["Ausgangslage", "Ergebnis", "Übertragbarkeit"],
        isNew: true,
        origin: "hermes",
      },
      {
        id: "skal.ausmusterung",
        phase: "skal",
        name: "Ausmusterung",
        agent: "A4",
        mode: "ai-draft",
        mayStart: ["APM", "ARCH"],
        approvers: [],
        veto: false,
        description: "Schlägt veraltete oder unsichere Lösungen zur Ablösung vor.",
        outputDoc: "Ausmusterungsvorschlag",
        sections: ["Betroffene Lösung", "Gründe", "Vorschlag zur Ablösung"],
        isNew: true,
        origin: "hermes",
      },
    ],
  },
];
